//- No programa principal, pergunte ao usuário qual forma ele deseja criar. Em seguida, para
//cada forma, solicite os dados necessários para criar a forma.  
//Todas as formas criadas devem ser armazenadas em um vetor. 
//Finalmente, imprima: (a) os dados (lados ou raio);
//(b) os perímetros; e (c) as áreas de todas as formas.
package visao;

import modelo.IFormaGeometrica;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class TelaInicial extends javax.swing.JFrame {

    ArrayList<IFormaGeometrica> lista = new ArrayList();
    
    /**
     * Creates new form MainForm
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public TelaInicial(ArrayList<IFormaGeometrica> dados) {
        initComponents();
        this.setLocationRelativeTo(null);
        for (int i = 0; i < dados.size(); i++) {
            lista.add(dados.get(i));
        }
        System.out.println(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btCirculo = new javax.swing.JButton();
        btRetangulo = new javax.swing.JButton();
        btQuadrado = new javax.swing.JButton();
        btTodosObjetos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Calculadora geométrica");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("1º) Selecione o objeto geométrico");

        btCirculo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btCirculo.setText("Circulo");
        btCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCirculoActionPerformed(evt);
            }
        });

        btRetangulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btRetangulo.setText("Retangulo");
        btRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetanguloActionPerformed(evt);
            }
        });

        btQuadrado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btQuadrado.setText("Quadrado");
        btQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuadradoActionPerformed(evt);
            }
        });

        btTodosObjetos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btTodosObjetos.setText("Mostrar objetos criados");
        btTodosObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTodosObjetosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btTodosObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCirculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRetangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQuadrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btTodosObjetos))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuadradoActionPerformed
        TelaQuadrado tela = new TelaQuadrado(lista);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btQuadradoActionPerformed

    private void btRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetanguloActionPerformed
       TelaRetangulo tela = new TelaRetangulo(lista);
       tela.setLocationRelativeTo(null);
       tela.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btRetanguloActionPerformed

    private void btCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCirculoActionPerformed
        TelaCirculo tela = new TelaCirculo(lista);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btCirculoActionPerformed

    private void btTodosObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTodosObjetosActionPerformed
        String temp;
        temp = "";
        for (int i = 0; i < lista.size(); i++) {
            temp += "--------------------\n"
                    + lista.get(i)
                    + "\nPerímetro: "  + lista.get(i).calcularPerimetro()
                    + "\nArea: " + lista.get(i).calcularArea()
                    + "\n--------------------\n";
        }
        JOptionPane.showMessageDialog(null, temp);
    }//GEN-LAST:event_btTodosObjetosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCirculo;
    private javax.swing.JButton btQuadrado;
    private javax.swing.JButton btRetangulo;
    private javax.swing.JButton btTodosObjetos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
