INSERT INTO DAWA_ENTITY (id, descricao, senha) VALUES (1, 'PRIMEIRA DESCRICAO', 111);
INSERT INTO DAWA_ENTITY (id, descricao, senha) VALUES (2, 'SEGUNDA DESCRICAO', 222);
INSERT INTO DAWA_ENTITY (id, descricao, senha) VALUES (3, 'TERCEIRA DESCRICAO', 333);