INSERT INTO DAWA_ENTITY (id, descricao) VALUES (1, 'PRIMEIRA DESCRICAO');
INSERT INTO DAWA_ENTITY (id, descricao) VALUES (2, 'SEGUNDA DESCRICAO');
INSERT INTO DAWA_ENTITY (id, descricao) VALUES (3, 'TERCEIRA DESCRICAO');